oro_importexport:
    label: General import/action operations
    type: action
    group_name: ""
    bindings: ~

oro_importexport_import:
    label: Import entities
    type: action
    group_name: ""
    bindings: ~

oro_importexport_export:
    label: Export entities
    type: action
    group_name: ""
    bindings: ~
