parameters:
    oro_importexport.data_converter.default.class: Oro\Bundle\ImportExportBundle\Converter\DefaultDataConverter
    oro_importexport.data_converter.configurable.class: Oro\Bundle\ImportExportBundle\Converter\ConfigurableTableDataConverter

services:
    oro_importexport.data_converter.default:
        class: %oro_importexport.data_converter.default.class%

    oro_importexport.data_converter.configurable:
        class: %oro_importexport.data_converter.configurable.class%
        abstract: true
        arguments:
            - @oro_entity.entity_field_provider
            - @oro_importexport.field.field_helper
