parameters:
    oro_importexport.field.field_helper.class: Oro\Bundle\ImportExportBundle\Field\FieldHelper

services:
    oro_importexport.field.field_helper:
        class: %oro_importexport.field.field_helper.class%
        arguments:
            - @oro_entity.entity_field_provider
            - @oro_entity_config.provider.importexport
            - @oro_entity_extend.extend.field_type_helper
