parameters:
    oro_importexport.form.type.import.class: Oro\Bundle\ImportExportBundle\Form\Type\ImportType
    oro_importexport.form.type.full_option.class: Oro\Bundle\ImportExportBundle\Form\Type\FullOptionType

services:
    oro_importexport.form.type.import:
        class: %oro_importexport.form.type.import.class%
        arguments: [@oro_importexport.processor.registry]
        tags:
            - { name: form.type, alias: oro_importexport_import }

    oro_importexport.form.type.full_option:
        class: %oro_importexport.form.type.full_option.class%
        arguments:
            - @oro_entity_extend.extend.field_type_helper
        tags:
            - { name: form.type, alias: oro_importexport_full_option }
