parameters:
    oro_importexport.processor.registry.class: Oro\Bundle\ImportExportBundle\Processor\ProcessorRegistry
    oro_importexport.processor.registry_delegate_processor.class: Oro\Bundle\ImportExportBundle\Processor\RegistryDelegateProcessor

services:
    # Import processor and registry
    oro_importexport.processor.import:
        class: %oro_importexport.processor.registry_delegate_processor.class%
        arguments: [@oro_importexport.processor.import_registry]

    oro_importexport.processor.import_registry:
        class: %oro_importexport.processor.registry.class%
        tags:
            - { name: oro_importexport.processor_registry, type: import }

    # Export processor and registry
    oro_importexport.processor.export:
        class: %oro_importexport.processor.registry_delegate_processor.class%
        arguments: [@oro_importexport.processor.export_registry]

    oro_importexport.processor.export_registry:
        class: %oro_importexport.processor.registry.class%
        tags:
            - { name: oro_importexport.processor_registry, type: export }

    # Import validate processor and registry
    oro_importexport.processor.validate_import:
        class: %oro_importexport.processor.registry_delegate_processor.class%
        arguments: [@oro_importexport.processor.validate_import_registry]

    oro_importexport.processor.validate_import_registry:
        class: %oro_importexport.processor.registry.class%
        tags:
            - { name: oro_importexport.processor_registry, type: validate_import }
