parameters:
    oro_importexport.processor.registry.class: Oro\Bundle\ImportExportBundle\Processor\ProcessorRegistry
    oro_importexport.processor.registry_delegate_processor.class: Oro\Bundle\ImportExportBundle\Processor\RegistryDelegateProcessor

    oro_importexport.processor.export_abstract.class: Oro\Bundle\ImportExportBundle\Processor\ExportProcessor
    oro_importexport.processor.import_abstract.class: Oro\Bundle\ImportExportBundle\Processor\ImportProcessor

services:
    # Import delegate processor, abstract import processor and registry
    oro_importexport.processor.import_delegate:
        class: %oro_importexport.processor.registry_delegate_processor.class%
        arguments: [@oro_importexport.processor.import_registry]

    oro_importexport.processor.import_registry:
        class: %oro_importexport.processor.registry.class%
        tags:
            - { name: oro_importexport.processor_registry, type: import }

    oro_importexport.processor.import_abstract:
        class: %oro_importexport.processor.import_abstract.class%
        abstract: true
        calls:
            - [setSerializer, [@oro_importexport.serializer]]

    # Export delegate processor, abstract import processor and registry
    oro_importexport.processor.export_delegate:
        class: %oro_importexport.processor.registry_delegate_processor.class%
        arguments: [@oro_importexport.processor.export_registry]

    oro_importexport.processor.export_registry:
        class: %oro_importexport.processor.registry.class%
        tags:
            - { name: oro_importexport.processor_registry, type: export }

    oro_importexport.processor.export_abstract:
        class: %oro_importexport.processor.export_abstract.class%
        abstract: true
        calls:
            - [setSerializer, [@oro_importexport.serializer]]

    # Import validate processor and registry
    oro_importexport.processor.validate_import_delegate:
        class: %oro_importexport.processor.registry_delegate_processor.class%
        arguments: [@oro_importexport.processor.validate_import_registry]

    oro_importexport.processor.validate_import_registry:
        class: %oro_importexport.processor.registry.class%
        tags:
            - { name: oro_importexport.processor_registry, type: validate_import }
