config:
    paths:
        'oroimportexport/js/importexport-manager': 'bundles/oroimportexport/js/importexport-manager.js'
        'oroimportexport/js/export-handler': 'bundles/oroimportexport/js/export-handler.js'
        'oroimportexport/js/app/views/import-export-buttons-view': 'bundles/oroimportexport/js/app/views/import-export-buttons-view.js'
