parameters:
    oro_importexport.value_converter.boolean.class:  Oro\Bundle\ImportExportBundle\ValueConverter\BooleanValueConverter
    oro_importexport.value_converter.datetime.class: Oro\Bundle\ImportExportBundle\ValueConverter\DateTimeValueConverter
    oro_importexport.value_converter.float.class:    Oro\Bundle\ImportExportBundle\ValueConverter\FloatValueConverter
    oro_importexport.value_converter.integer.class:  Oro\Bundle\ImportExportBundle\ValueConverter\IntegerValueConverter
    oro_importexport.value_converter.string.class:   Oro\Bundle\ImportExportBundle\ValueConverter\StringValueConverter

services:
    oro_importexport.value_converter.string:
        class: %oro_importexport.value_converter.string.class%
        tags:
            - { name: oro_importexport.value_converter, alias: doctrine_string }

    oro_importexport.value_converter.integer:
        class: %oro_importexport.value_converter.integer.class%
        tags:
            - { name: oro_importexport.value_converter, alias: doctrine_integer }

    oro_importexport.value_converter.smallint:
        class: %oro_importexport.value_converter.integer.class%
        tags:
            - { name: oro_importexport.value_converter, alias: doctrine_smallint }

    oro_importexport.value_converter.bigint:
        class: %oro_importexport.value_converter.integer.class%
        tags:
            - { name: oro_importexport.value_converter, alias: doctrine_bigint }

    oro_importexport.value_converter.boolean:
        class: %oro_importexport.value_converter.boolean.class%
        tags:
            - { name: oro_importexport.value_converter, alias: doctrine_boolean }

    oro_importexport.value_converter.decimal:
        class: %oro_importexport.value_converter.float.class%
        tags:
            - { name: oro_importexport.value_converter, alias: doctrine_decimal }

    oro_importexport.value_converter.date:
        class: %oro_importexport.value_converter.datetime.class%
        tags:
            - { name: oro_importexport.value_converter, alias: doctrine_date }

    oro_importexport.value_converter.time:
        class: %oro_importexport.value_converter.datetime.class%
        tags:
            - { name: oro_importexport.value_converter, alias: doctrine_time }

    oro_importexport.value_converter.datetime:
        class: %oro_importexport.value_converter.datetime.class%
        tags:
            - { name: oro_importexport.value_converter, alias: doctrine_datetime }

    oro_importexport.value_converter.text:
        class: %oro_importexport.value_converter.string.class%
        tags:
            - { name: oro_importexport.value_converter, alias: doctrine_text }

    oro_importexport.value_converter.float:
        class: %oro_importexport.value_converter.float.class%
        tags:
            - { name: oro_importexport.value_converter, alias: doctrine_float }


