parameters:
    oro_importexport.writer.csv.class: Oro\Bundle\ImportExportBundle\Writer\CsvFileWriter
    oro_importexport.writer.entity.class: Oro\Bundle\ImportExportBundle\Writer\EntityWriter
    oro_importexport.writer.dummy.class: Oro\Bundle\ImportExportBundle\Writer\DummyWriter

services:
    oro_importexport.writer.csv:
        class: %oro_importexport.writer.csv.class%
        arguments:
            - @oro_importexport.context_registry

    oro_importexport.writer.entity:
        class: %oro_importexport.writer.entity.class%
        arguments:
            - @doctrine.orm.entity_manager

    oro_importexport.writer.dummy:
        class: %oro_importexport.writer.dummy.class%
        arguments:
            - @doctrine.orm.entity_manager
